### PR TITLE
Add utility for adding datestamp for gc.log files without it

### PR DESCRIPTION
**Pull request by alfh**
Sometimes you have gc.log files without datestamps as first column,
either because you are running an old JDK (1.4 or 5), which does
not support -XX:+PrintGCDateStamps.
Or simply because you have not used -XX:+PrintGCDateStamps when
starting the java process.

This utility allows you to add the datestamp column, if you know
the start time of the java process that has generated the
gc.log files.

If you do not know the process start time, you can just pick a
date, but then you cannot correlate the gc graphs with other
graphs, for example sar graphs.

### CODE REVIEW

**Comment by richardhsu** [comment]
This utility will also need to be added to `scripts` in `naarad/setup.py` so it can be packaged with the naarad.

**Comment by joyxiong** [comment]
As setup.py is to pre-process a file, I recommend we have a separate directory for these types of scripts.

**Comment by richardhsu** [comment]
What might be a good location?

We could make a `utilities` folder at the top level? Or under `lib` create a `utilities` folder?

**Comment by joyxiong** [comment]
I like the folder named as utilities.
As the utilities won’t be used by naarad itself, I feel it a better option to have the folder at the top level instead of under lib.

**Comment by RiteshMaheshwari** [comment]
We can keep it in /bin, I am not sure I follow the reasoning for moving this to another directory.

**Comment by alfh** [comment]
I've now added a commit to update the setup.py

**Comment by richardhsu** [comment]
If we need to split out to another folder we will but for now since this is a preprocessing script similar to the GC one we currently have, leaving in bin is fine. Thanks for the updates @alfh

**Pull request merged**
