### PR TITLE
fix for bug 310

### PR DESCRIPTION
**Pull request by feng-tao**
Based on Richard's fix( richardhsu@1fea49f ), do some modification. Currently the time series is inserted into csv file with unix time timestamp

### CODE REVIEW

**Comment by feng-tao** [comment]
hi, anyone got a chance to review this fix?

**Comment by richardhsu** [comment]
I will try to review in the next 2 days :)

**Comment by richardhsu** [comment]
Code looks good so far. I have tested this against a report I generated today for PROCZONEINFO, PROCMEMINFO, and PROCVMSTAT, SAR and CSVs and the graph are generated nicely with the correct UTC times. I have not looked at TOP, generic metrics, jmeter, or any other parsers yet though.

@feng-tao  have you tested any of these by any chance?

**Comment by stefanodoni** [comment]
Hi,

I'm testing naarad - thanks, much needed tool! - and I'm too having issues with timezones.

I'm analyzing:
- GC log generated with UTC timestamps (due to the Java app specifics settings)
- Linux sar log generated in local timezone (UTC+2)

When I import the two logs in naarad, apart from file parsing issues (I'll file separate bugs for that), what I got in the UI is that:
- the GC logs are kept in the original timezone, UTC
- the sar logs gets shifted two hours ahead, resulting in UTC + 4

The end result is of course that you cannot do any meaningful correlation analysis :(

So far I have hardcoded a -4 hours time shift in the sar_metric.py parser, which is of course just a hack.

How can I tell naarad the timezone of the different data sources?

I see a timezone option in the GRAPH setting, however a) it is not data source specific and b) it seems not to support timezones other than US or UTC.

**Pull request closed without merging**
